import { Injectable, signal } from '@angular/core';
import { Product } from './product.model';

@Injectable({ providedIn: 'root' })
export class ProductDataService {

  readonly products = signal<Product[]>([
    {
      id: 1,
      name: 'RevenueAnalyticsCore_Customer_LifetimeValue_SupplyChainVelocity_WorkforcePlanningModel_MarketingAttribution_RiskExposureDashboard_ProductUsageTelemetry_FinancialCloseAccelerator',
      description:
        'Consolidated revenue streams across all business units with YoY growth metrics, margin analysis, and forecast accuracy tracking.',
      owner: 'Sarah Chen',
      connected_count: 14,
      content_url: 'https://tableau.company.com/views/revenue-analytics',
      product_createdAt: new Date('2023-11-01'),
      product_updatedAt: new Date('2025-02-08'),
      has_extracts: true,
      is_certified_on_source: true,
      is_certified_on_bi_platform: true,
      is_published: true,
      size: 248_000_000,
      webPageUrl: 'https://bi-hub.company.com/products/revenue-analytics-core',
      sourceDisplayName: 'Snowflake — ANALYTICS.REVENUE_V2',
    },
    {
      id: 2,
      name: 'Customer Lifetime ValueCustomer Lifetime ValueCustomer Lifetime ValueCustomer Lifetime ValueCustomer Lifetime ValueCustomer Lifetime ValueCustomer Lifetime ValueCustomer Lifetime ValueCustomer Lifetime ValueCustomer Lifetime ValueCustomer Lifetime Value',
      description:
        'CLV computation engine combining transactional history, engagement scores, and churn probability for segmentation.',
      owner: 'Marcus Webb',
      connected_count: 8,
      content_url: 'https://tableau.company.com/views/clv-model',
      product_createdAt: new Date('2024-01-15'),
      product_updatedAt: new Date('2025-01-25'),
      has_extracts: true,
      is_certified_on_source: true,
      is_certified_on_bi_platform: true,
      is_published: true,
      size: 112_000_000,
      webPageUrl: 'https://bi-hub.company.com/products/clv',
      sourceDisplayName: 'Snowflake — ANALYTICS.CLV_MASTER',
    },
    {
      id: 3,
      name: 'Supply Chain Velocity',
      description:
        'End-to-end supply chain metrics from procurement through delivery, including lead times, bottleneck identification, and vendor scorecards.',
      owner: 'Anika Patel',
      connected_count: 5,
      content_url: 'https://tableau.company.com/views/supply-chain',
      product_createdAt: new Date('2024-05-20'),
      product_updatedAt: new Date('2025-02-12'),
      has_extracts: false,
      is_certified_on_source: false,
      is_certified_on_bi_platform: false,
      is_published: true,
      size: 67_500_000,
      webPageUrl: 'https://bi-hub.company.com/products/supply-chain-velocity',
      sourceDisplayName: 'Snowflake — OPS.SUPPLY_CHAIN_V1',
    },
    {
      id: 4,
      name: 'Workforce Planning Model',
      description:
        'Headcount forecasting with attrition modeling, skills gap analysis, and capacity planning across departments.',
      owner: 'James Thornton',
      connected_count: 2,
      content_url: 'https://powerbi.company.com/reports/workforce',
      product_createdAt: new Date('2024-08-12'),
      product_updatedAt: new Date('2025-02-14'),
      has_extracts: false,
      is_certified_on_source: false,
      is_certified_on_bi_platform: false,
      is_published: false,
      size: 23_400_000,
      webPageUrl: 'https://bi-hub.company.com/products/workforce-planning',
      sourceDisplayName: 'Snowflake — HR.WORKFORCE_PLANNING',
    },
    {
      id: 5,
      name: 'Marketing Attribution',
      description:
        'Multi-touch attribution model mapping campaign spend to conversion events across digital and offline channels.',
      owner: 'Sarah Chen',
      connected_count: 11,
      content_url: 'https://tableau.company.com/views/marketing-attribution',
      product_createdAt: new Date('2024-02-28'),
      product_updatedAt: new Date('2025-01-30'),
      has_extracts: true,
      is_certified_on_source: true,
      is_certified_on_bi_platform: true,
      is_published: true,
      size: 185_000_000,
      webPageUrl: 'https://bi-hub.company.com/products/marketing-attribution',
      sourceDisplayName: 'Snowflake — MARKETING.ATTRIBUTION_MODEL',
    },
    {
      id: 6,
      name: 'Risk Exposure Dashboard',
      description:
        'Real-time risk scoring aggregating market, credit, and operational risk factors with regulatory threshold alerts.',
      owner: 'Elena Vasquez',
      connected_count: 3,
      content_url: 'https://powerbi.company.com/reports/risk-exposure',
      product_createdAt: new Date('2024-10-01'),
      product_updatedAt: new Date('2025-02-15'),
      has_extracts: false,
      is_certified_on_source: false,
      is_certified_on_bi_platform: false,
      is_published: false,
      size: 41_200_000,
      webPageUrl: 'https://bi-hub.company.com/products/risk-exposure',
      sourceDisplayName: 'Snowflake — RISK.EXPOSURE_REALTIME',
    },
    {
      id: 7,
      name: 'Product Usage Telemetry',
      description:
        'Feature adoption and usage patterns across product lines with cohort analysis and engagement scoring.',
      owner: 'David Kim',
      connected_count: 9,
      content_url: 'https://tableau.company.com/views/usage-telemetry',
      product_createdAt: new Date('2024-04-10'),
      product_updatedAt: new Date('2025-02-09'),
      has_extracts: true,
      is_certified_on_source: true,
      is_certified_on_bi_platform: true,
      is_published: true,
      size: 320_000_000,
      webPageUrl: 'https://bi-hub.company.com/products/usage-telemetry',
      sourceDisplayName: 'Snowflake — PRODUCT.TELEMETRY_EVENTS',
    },
    {
      id: 8,
      name: 'Financial Close Accelerator',
      description:
        'Automated reconciliation datasets for month-end close with variance detection and audit trail lineage.',
      owner: 'Marcus Webb',
      connected_count: 6,
      content_url: 'https://tableau.company.com/views/financial-close',
      product_createdAt: new Date('2024-09-15'),
      product_updatedAt: new Date('2025-02-13'),
      has_extracts: true,
      is_certified_on_source: true,
      is_certified_on_bi_platform: true,
      is_published: true,
      size: 156_000_000,
      webPageUrl: 'https://bi-hub.company.com/products/financial-close',
      sourceDisplayName: 'Snowflake — FINANCE.RECONCILIATION_V3',
    },
  ]);
}